// Dragon Codex: presentation only; no state, saves, or engine changes.
ThemeKit.register({
  "id": "dragon-codex",
  "name": "Dragon Codex",
  "author": "Codex",
  "title": "Dragon Codex",
  "fonts": "https://fonts.googleapis.com/css2?family=Uncial+Antiqua&family=Alegreya:wght@400;500;600;700;800&display=swap",
  "phrases": {
    "Snake Forever": "Dragon Codex",
    "SNAKE FOREVER": "DRAGON CODEX",
    "Menu": "Scribe\u2019s Desk",
    "Seeds": "Gold",
    "Seed": "Gold",
    "Branches": "Timber",
    "Branch": "Timber",
    "Provisions": "Rations",
    "Provision": "Ration",
    "Upgrades": "Arts",
    "Upgrade": "Improve",
    "Nursery": "Clutch",
    "Colony": "Realm",
    "Settle": "Fiefs",
    "Board size": "Folio size",
    "Food type": "Tribute type",
    "Food count": "Tribute count",
    "Shields": "Wards",
    "Shield": "Ward",
    "Minigames": "Trials",
    "Minigame": "Trial",
    "Pod I": "Coin I",
    "Pod II": "Coin II",
    "Pod III": "Coin III",
    "Fruit I": "Gem I",
    "Fruit II": "Gem II",
    "Fruit III": "Gem III",
    "Snacks": "Offerings",
    "Snack": "Offering",
    "Add Nest Slot": "Add Clutch Slot",
    "Nest Slots": "Clutch Slots",
    "Nest Slot": "Clutch Slot",
    "Nests": "Clutches",
    "Nest": "Clutch",
    "Eggs": "Dragon eggs",
    "Egg": "Dragon egg",
    "Hatchling yard": "Wyrmling court",
    "Hatchlings": "Wyrmlings",
    "Hatchling": "Wyrmling",
    "Pause feeding": "Pause feeding",
    "Resume feeding": "Resume feeding",
    "Upgrade Nursery": "Expand Clutch",
    "Incubation box": "Hatchery",
    "Hatching": "Awakening",
    "Habitats": "Lairs",
    "Habitat": "Lair",
    "Field": "Meadow",
    "Lake": "Mere",
    "Forest": "Greenwood",
    "River": "Waterway",
    "Cave": "Grotto",
    "Ocean": "Sapphire",
    "Mountain": "High Keep",
    "Blizzard": "Frosthold",
    "Notables": "Champions",
    "Notable": "Champion",
    "Elders": "Ancients",
    "Elder": "Ancient",
    "Candidates": "Petitioners",
    "Candidate": "Petitioner",
    "Recruit Notable": "Recruit Champion",
    "Adults": "Dragons",
    "Adult": "Dragon",
    "Convoys": "Caravans",
    "Convoy": "Caravan",
    "Settlements": "Fiefs",
    "Settlement": "Fief",
    "Grasslands": "Crownlands",
    "Expeditions": "Quests",
    "Expedition": "Quest",
    "Wetlands": "Fenlands",
    "Highlands": "Crown Peaks",
    "Badlands": "Ashlands",
    "Coast": "Dragonshore",
    "Trade": "Barter",
    "MP": "Renown",
    "Snakes": "Wyrms",
    "Snake": "Wyrm",
    "Personalization": "Personalization",
    "Personalize": "Personalize",
    "PHONE": "CODEX",
    "Score": "Hoard",
    "Best": "Legend",
    "Moves": "Steps",
    "Grid": "Folio",
    "Ready": "Ready",
    "Paused": "Paused",
    "Game Over": "Tale Ended",
    "Vs Snake": "Wyrm Duel",
    "Snakeger": "Ford Trial",
    "Brick Breakout": "Siege Breaker",
    "Snake Runner": "Wyrm Flight",
    "Centipede": "Hydra",
    "Broodline": "Dragonflight",
    "Venom Strike": "Corsair Duel",
    "Snakebird": "Wyrmwing",
    "Sokoban": "Vault Keeper",
    "Maze": "Labyrinth",
    "Crossing": "Ford",
    "Titanoboa": "Leviathan",
    "Anaconda": "Basilisk",
    "Python": "Wyvern",
    "Viper": "Drake",
    "Adder": "Whelp",
    "Moss": "Lapis",
    "Dark purple": "Amethyst",
    "Teal": "Verdigris",
    "Ember": "Cinnabar",
    "Orange": "Ochre",
    "Berry": "Madder",
    "Charcoal": "Iron Ink",
    "Violet": "Iris",
    "Sky": "Azurite",
    "Mint": "Malachite",
    "Ruby": "Vermilion",
    "Gold": "Gold Leaf",
    "Plum": "Mulberry",
    "Slate": "Pewter",
    "Re-Supply": "Re-Supply",
    "Garden": "Grove",
    "Electric": "Storm",
    "Lava": "Emberwing",
    "Rattle": "Bell",
    "Body": "Scales",
    "Head": "Crown",
    "Formation": "Flight Formation",
    "Games": "Trials",
    "Start": "Start",
    "Pause": "Pause",
    "Reset": "Reset",
    "Resume": "Resume",
    "Reduced motion": "Reduced motion",
    "Back": "Back",
    "Settings": "Settings",
    "Phone Mode": "Phone Mode",
    "Import": "Import",
    "Save data": "Save data",
    "snake forever": "dragon codex",
    "menu": "scribe\u2019s desk",
    "seeds": "gold",
    "seed": "gold",
    "branches": "timber",
    "branch": "timber",
    "provisions": "rations",
    "provision": "ration",
    "upgrades": "arts",
    "upgrade": "improve",
    "nursery": "clutch",
    "colony": "realm",
    "settle": "fiefs",
    "board size": "folio size",
    "food type": "tribute type",
    "food count": "tribute count",
    "shields": "wards",
    "shield": "ward",
    "minigames": "trials",
    "minigame": "trial",
    "pod i": "coin i",
    "pod ii": "coin ii",
    "pod iii": "coin iii",
    "fruit i": "gem i",
    "fruit ii": "gem ii",
    "fruit iii": "gem iii",
    "snacks": "offerings",
    "snack": "offering",
    "add nest slot": "add clutch slot",
    "nest slots": "clutch slots",
    "nest slot": "clutch slot",
    "nests": "clutches",
    "nest": "clutch",
    "eggs": "dragon eggs",
    "egg": "dragon egg",
    "hatchling yard": "wyrmling court",
    "hatchlings": "wyrmlings",
    "hatchling": "wyrmling",
    "pause feeding": "pause feeding",
    "resume feeding": "resume feeding",
    "upgrade nursery": "expand clutch",
    "incubation box": "hatchery",
    "hatching": "awakening",
    "habitats": "lairs",
    "habitat": "lair",
    "field": "meadow",
    "lake": "mere",
    "forest": "greenwood",
    "river": "waterway",
    "cave": "grotto",
    "ocean": "sapphire",
    "mountain": "high keep",
    "blizzard": "frosthold",
    "notables": "champions",
    "notable": "champion",
    "elders": "ancients",
    "elder": "ancient",
    "candidates": "petitioners",
    "candidate": "petitioner",
    "recruit notable": "recruit champion",
    "adults": "dragons",
    "adult": "dragon",
    "convoys": "caravans",
    "convoy": "caravan",
    "settlements": "fiefs",
    "settlement": "fief",
    "grasslands": "crownlands",
    "expeditions": "quests",
    "expedition": "quest",
    "wetlands": "fenlands",
    "highlands": "crown peaks",
    "badlands": "ashlands",
    "coast": "dragonshore",
    "trade": "barter",
    "snakes": "wyrms",
    "snake": "wyrm",
    "personalization": "personalization",
    "personalize": "personalize",
    "score": "hoard",
    "best": "legend",
    "moves": "steps",
    "grid": "folio",
    "ready": "ready",
    "paused": "paused",
    "game over": "tale ended",
    "vs snake": "wyrm duel",
    "snakeger": "ford trial",
    "brick breakout": "siege breaker",
    "snake runner": "wyrm flight",
    "centipede": "hydra",
    "broodline": "dragonflight",
    "venom strike": "corsair duel",
    "snakebird": "wyrmwing",
    "sokoban": "vault keeper",
    "maze": "labyrinth",
    "crossing": "ford",
    "titanoboa": "leviathan",
    "anaconda": "basilisk",
    "python": "wyvern",
    "viper": "drake",
    "adder": "whelp",
    "moss": "lapis",
    "dark purple": "amethyst",
    "teal": "verdigris",
    "ember": "cinnabar",
    "orange": "ochre",
    "berry": "madder",
    "charcoal": "iron ink",
    "violet": "iris",
    "sky": "azurite",
    "mint": "malachite",
    "ruby": "vermilion",
    "gold": "gold leaf",
    "plum": "mulberry",
    "slate": "pewter",
    "re-supply": "re-supply",
    "garden": "grove",
    "electric": "storm",
    "lava": "emberwing",
    "rattle": "bell",
    "body": "scales",
    "head": "crown",
    "formation": "flight formation",
    "games": "trials",
    "start": "start",
    "pause": "pause",
    "reset": "reset",
    "resume": "resume",
    "reduced motion": "reduced motion",
    "back": "back",
    "settings": "settings",
    "phone mode": "phone mode",
    "import": "import",
    "save data": "save data",
    "\u2726": "\u2725",
    "\u2665": "\u2665",
    "\u2190": "\u2190",
    "\u2192": "\u2192",
    "\u2191": "\u2191",
    "\u2193": "\u2193"
  },
  "canvas": {
    "colors": {
      "#9cac77": "#f0dfb3",
      "#182413": "#29213b",
      "#29391f": "#31466e",
      "#e7e1c5": "#a86b25",
      "#101713": "#fff5d6",
      "#4b562f": "#7b5232",
      "#f2e9ba": "#e2b65c",
      "#52beff": "#c09738",
      "#4aafff": "#927023",
      "#e4c65e": "#a15c17",
      "#fffdf0": "#ad391f",
      "#d5d5c8": "#c47844",
      "#718253": "#877143",
      "#a55b25": "#9c571e",
      "#4b3d2a": "#574032",
      "#708b59": "#cbbb8e",
      "#344336": "#b9a77c",
      "#38502a": "#46546e",
      "#496536": "#7c4a50",
      "#5c7840": "#836328",
      "#b3483d": "#ae3329",
      "#586e3a": "#7c6035",
      "#2d8b68": "#287153",
      "#16231d": "#ecdbb2",
      "#243b2a": "#e1cfa5",
      "#29452f": "#e8d7b0",
      "#d5df9d": "#76552b",
      "#67c993": "#397750",
      "#8fa6d6": "#5867a0",
      "#d9d45a": "#9e751a",
      "#e37a47": "#b85626",
      "#b996cf": "#7b4e92",
      "#91b957": "#657438",
      "#d58964": "#a15424",
      "#c4574e": "#973134",
      "#132218": "#3a2931",
      "#1b2b20": "#fff4d6",
      "#1c2c22": "#694c3d",
      "#f6e8a4": "#fff0c2",
      "#efe7b4": "#d3a340",
      "#e5a04c": "#bb7229",
      "#e0c15a": "#c19a38",
      "#f4d39a": "#f9e5af",
      "#d0574e": "#c2482a",
      "#7bc86c": "#78a363",
      "#0a100c": "#2b2131",
      "#ffffff": "#fff4d2",
      "#32204f": "#503571",
      "#16465a": "#255d82",
      "#176052": "#28706d",
      "#843b2f": "#923e2e",
      "#702c57": "#8b385d",
      "#252a32": "#3d3541",
      "#583b83": "#775093",
      "#267b91": "#307ca1",
      "#b0802d": "#9c771d",
      "#9b477e": "#ab5071",
      "#596474": "#626375"
    },
    "fonts": {
      "Courier New": "Alegreya"
    },
    "scanlines": false,

    overlay(ctx, canvas, metrics, strength = 1) {
      const w = canvas.width, h = canvas.height;
      if (w < 12 || h < 12) return;
      ctx.save();
      ctx.globalAlpha = Math.min(1, Math.max(0, strength));
      // Static parchment fibres: 48 tiny marks, no random numbers or frame caches.
      ctx.fillStyle = "rgba(116, 78, 34, 0.085)";
      for (let i = 0; i < 48; i += 1) {
        ctx.fillRect((i * 73 + 19) % w, (i * 131 + 37) % h, 1 + i % 3, 1);
      }
      // Gilt marginalia stays at the canvas edge, clear of cells and the HUD.
      ctx.strokeStyle = "rgba(145, 100, 29, 0.48)";
      ctx.lineWidth = 1;
      ctx.strokeRect(1.5, 1.5, w - 3, h - 3);
      ctx.fillStyle = "rgba(158, 49, 34, 0.55)";
      for (let i = 0; i < 4; i += 1) {
        const x = i % 2 ? w - 4 : 4, y = i < 2 ? 4 : h - 4;
        ctx.beginPath();
        ctx.moveTo(x, y - 2); ctx.lineTo(x + 2, y);
        ctx.lineTo(x, y + 2); ctx.lineTo(x - 2, y);
        ctx.closePath(); ctx.fill();
      }
      ctx.restore();
    }
  }
});
