// Polar Sled: presentation only; no state, saves, or engine changes.
ThemeKit.register({
  "id": "polar-sled",
  "name": "Polar Sled",
  "author": "Codex",
  "title": "Polar Sled",
  "fonts": "https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=Barlow:wght@400;500;600;700;800&display=swap",
  "phrases": {
    "Snake Forever": "Polar Sled",
    "SNAKE FOREVER": "POLAR SLED",
    "Menu": "Field Station",
    "Seeds": "Fish",
    "Seed": "Fish",
    "Branches": "Lumber",
    "Branch": "Lumber",
    "Provisions": "Kibble",
    "Provision": "Kibble",
    "Upgrades": "Gear",
    "Upgrade": "Improve",
    "Nursery": "Kennel",
    "Colony": "Camps",
    "Settle": "Posts",
    "Board size": "Map size",
    "Food type": "Catch type",
    "Food count": "Catch count",
    "Shields": "Guards",
    "Shield": "Guard",
    "Minigames": "Missions",
    "Minigame": "Mission",
    "Pod I": "Char I",
    "Pod II": "Char II",
    "Pod III": "Char III",
    "Fruit I": "Salmon I",
    "Fruit II": "Salmon II",
    "Fruit III": "Salmon III",
    "Snacks": "Catches",
    "Snack": "Catch",
    "Add Nest Slot": "Add Den Slot",
    "Nest Slots": "Den Slots",
    "Nest Slot": "Den Slot",
    "Nests": "Dens",
    "Nest": "Den",
    "Eggs": "Pup bundles",
    "Egg": "Pup bundle",
    "Hatchling yard": "Pup yard",
    "Hatchlings": "Pups",
    "Hatchling": "Pup",
    "Pause feeding": "Pause feeding",
    "Resume feeding": "Resume feeding",
    "Upgrade Nursery": "Expand Kennel",
    "Incubation box": "Warming den",
    "Hatching": "Waking",
    "Habitats": "Base camps",
    "Habitat": "Base camp",
    "Field": "Tundra",
    "Lake": "Ice Lake",
    "Forest": "Taiga",
    "River": "Ice Run",
    "Cave": "Ice Den",
    "Ocean": "Fjord",
    "Mountain": "Summit",
    "Blizzard": "Whiteout",
    "Notables": "Guides",
    "Notable": "Guide",
    "Elders": "Veterans",
    "Elder": "Veteran",
    "Candidates": "Applicants",
    "Candidate": "Applicant",
    "Recruit Notable": "Recruit Guide",
    "Adults": "Sled dogs",
    "Adult": "Sled dog",
    "Convoys": "Sled trains",
    "Convoy": "Sled train",
    "Settlements": "Outposts",
    "Settlement": "Outpost",
    "Grasslands": "Home Tundra",
    "Expeditions": "Treks",
    "Expedition": "Trek",
    "Wetlands": "Thaw Marsh",
    "Highlands": "Ice Ridge",
    "Badlands": "Bare Rock",
    "Coast": "Pack Ice",
    "Trade": "Exchange",
    "MP": "Trail Points",
    "Snakes": "Dog teams",
    "Snake": "Dog team",
    "Personalization": "Personalization",
    "Personalize": "Personalize",
    "PHONE": "RADIO",
    "Score": "Catch",
    "Best": "Record",
    "Moves": "Steps",
    "Grid": "Map",
    "Ready": "Ready",
    "Paused": "Paused",
    "Game Over": "Trail Ended",
    "Vs Snake": "Sled Duel",
    "Snakeger": "Ice Crossing",
    "Brick Breakout": "Ice Breaker",
    "Snake Runner": "Sled Sprint",
    "Centipede": "Snow Serpent",
    "Broodline": "Dogline",
    "Venom Strike": "Ice Patrol",
    "Snakebird": "Ridge Climb",
    "Sokoban": "Supply Cache",
    "Maze": "Ice Maze",
    "Crossing": "Ice Crossing",
    "Titanoboa": "Icebreaker",
    "Anaconda": "Research Ship",
    "Python": "Cutter",
    "Viper": "Skiff",
    "Adder": "Kayak",
    "Moss": "Denim",
    "Dark purple": "Polar Night",
    "Teal": "Glacier",
    "Ember": "Rust",
    "Orange": "Parka",
    "Berry": "Rosehip",
    "Charcoal": "Graphite",
    "Violet": "Aurora Violet",
    "Sky": "Ice Blue",
    "Mint": "Aurora Green",
    "Ruby": "Signal Red",
    "Gold": "Brass",
    "Plum": "Heather",
    "Slate": "Steel",
    "Re-Supply": "Re-Supply",
    "Garden": "Tundra",
    "Electric": "Aurora",
    "Lava": "Sunrise",
    "Rattle": "Snowbell",
    "Body": "Harness",
    "Head": "Lead",
    "Formation": "Team Formation",
    "Games": "Missions",
    "Start": "Start",
    "Pause": "Pause",
    "Reset": "Reset",
    "Resume": "Resume",
    "Reduced motion": "Reduced motion",
    "Back": "Back",
    "Settings": "Settings",
    "Phone Mode": "Phone Mode",
    "Import": "Import",
    "Save data": "Save data",
    "snake forever": "polar sled",
    "menu": "field station",
    "seeds": "fish",
    "seed": "fish",
    "branches": "lumber",
    "branch": "lumber",
    "provisions": "kibble",
    "provision": "kibble",
    "upgrades": "gear",
    "upgrade": "improve",
    "nursery": "kennel",
    "colony": "camps",
    "settle": "posts",
    "board size": "map size",
    "food type": "catch type",
    "food count": "catch count",
    "shields": "guards",
    "shield": "guard",
    "minigames": "missions",
    "minigame": "mission",
    "pod i": "char i",
    "pod ii": "char ii",
    "pod iii": "char iii",
    "fruit i": "salmon i",
    "fruit ii": "salmon ii",
    "fruit iii": "salmon iii",
    "snacks": "catches",
    "snack": "catch",
    "add nest slot": "add den slot",
    "nest slots": "den slots",
    "nest slot": "den slot",
    "nests": "dens",
    "nest": "den",
    "eggs": "pup bundles",
    "egg": "pup bundle",
    "hatchling yard": "pup yard",
    "hatchlings": "pups",
    "hatchling": "pup",
    "pause feeding": "pause feeding",
    "resume feeding": "resume feeding",
    "upgrade nursery": "expand kennel",
    "incubation box": "warming den",
    "hatching": "waking",
    "habitats": "base camps",
    "habitat": "base camp",
    "field": "tundra",
    "lake": "ice lake",
    "forest": "taiga",
    "river": "ice run",
    "cave": "ice den",
    "ocean": "fjord",
    "mountain": "summit",
    "blizzard": "whiteout",
    "notables": "guides",
    "notable": "guide",
    "elders": "veterans",
    "elder": "veteran",
    "candidates": "applicants",
    "candidate": "applicant",
    "recruit notable": "recruit guide",
    "adults": "sled dogs",
    "adult": "sled dog",
    "convoys": "sled trains",
    "convoy": "sled train",
    "settlements": "outposts",
    "settlement": "outpost",
    "grasslands": "home tundra",
    "expeditions": "treks",
    "expedition": "trek",
    "wetlands": "thaw marsh",
    "highlands": "ice ridge",
    "badlands": "bare rock",
    "coast": "pack ice",
    "trade": "exchange",
    "snakes": "dog teams",
    "snake": "dog team",
    "personalization": "personalization",
    "personalize": "personalize",
    "score": "catch",
    "best": "record",
    "moves": "steps",
    "grid": "map",
    "ready": "ready",
    "paused": "paused",
    "game over": "trail ended",
    "vs snake": "sled duel",
    "snakeger": "ice crossing",
    "brick breakout": "ice breaker",
    "snake runner": "sled sprint",
    "centipede": "snow serpent",
    "broodline": "dogline",
    "venom strike": "ice patrol",
    "snakebird": "ridge climb",
    "sokoban": "supply cache",
    "maze": "ice maze",
    "crossing": "ice crossing",
    "titanoboa": "icebreaker",
    "anaconda": "research ship",
    "python": "cutter",
    "viper": "skiff",
    "adder": "kayak",
    "moss": "denim",
    "dark purple": "polar night",
    "teal": "glacier",
    "ember": "rust",
    "orange": "parka",
    "berry": "rosehip",
    "charcoal": "graphite",
    "violet": "aurora violet",
    "sky": "ice blue",
    "mint": "aurora green",
    "ruby": "signal red",
    "gold": "brass",
    "plum": "heather",
    "slate": "steel",
    "re-supply": "re-supply",
    "garden": "tundra",
    "electric": "aurora",
    "lava": "sunrise",
    "rattle": "snowbell",
    "body": "harness",
    "head": "lead",
    "formation": "team formation",
    "games": "missions",
    "start": "start",
    "pause": "pause",
    "reset": "reset",
    "resume": "resume",
    "reduced motion": "reduced motion",
    "back": "back",
    "settings": "settings",
    "phone mode": "phone mode",
    "import": "import",
    "save data": "save data",
    "\u2726": "\u2744",
    "\u2665": "\u2665",
    "\u2190": "\u2190",
    "\u2192": "\u2192",
    "\u2191": "\u2191",
    "\u2193": "\u2193"
  },
  "canvas": {
    "colors": {
      "#9cac77": "#d9edf2",
      "#182413": "#16394b",
      "#29391f": "#306582",
      "#e7e1c5": "#b95120",
      "#101713": "#f6fcff",
      "#4b562f": "#627b91",
      "#f2e9ba": "#e7bd7f",
      "#52beff": "#34ad95",
      "#4aafff": "#8c72c4",
      "#e4c65e": "#b65825",
      "#fffdf0": "#ad4926",
      "#d5d5c8": "#cf7640",
      "#718253": "#688a99",
      "#a55b25": "#b25a2b",
      "#4b3d2a": "#4f5e76",
      "#708b59": "#c5e0e7",
      "#344336": "#adcbd7",
      "#38502a": "#486c91",
      "#496536": "#667caa",
      "#5c7840": "#8c71a5",
      "#b3483d": "#b13d4b",
      "#586e3a": "#526f98",
      "#2d8b68": "#247964",
      "#16231d": "#d5e9ee",
      "#243b2a": "#c8dfe7",
      "#29452f": "#d1e5eb",
      "#d5df9d": "#587e95",
      "#67c993": "#247c69",
      "#8fa6d6": "#667cba",
      "#d9d45a": "#9a771c",
      "#e37a47": "#b85e29",
      "#b996cf": "#8b60ad",
      "#91b957": "#428770",
      "#d58964": "#bc6d35",
      "#c4574e": "#b94351",
      "#132218": "#244a60",
      "#1b2b20": "#f1fbff",
      "#1c2c22": "#4f6f82",
      "#f6e8a4": "#f6fcff",
      "#efe7b4": "#d9b177",
      "#e5a04c": "#b86424",
      "#e0c15a": "#c39436",
      "#f4d39a": "#ffdfaa",
      "#d0574e": "#c64e49",
      "#7bc86c": "#62b591",
      "#0a100c": "#123246",
      "#ffffff": "#f7fcff",
      "#32204f": "#4b417e",
      "#16465a": "#255b79",
      "#176052": "#267378",
      "#843b2f": "#9c493b",
      "#702c57": "#91466f",
      "#252a32": "#35485d",
      "#583b83": "#7458a0",
      "#267b91": "#337dae",
      "#b0802d": "#ab7824",
      "#9b477e": "#aa5c91",
      "#596474": "#667c94"
    },
    "fonts": {
      "Courier New": "Barlow"
    },
    "scanlines": false,

    overlay(ctx, canvas, metrics, strength = 1) {
      const w = canvas.width, h = canvas.height;
      if (w < 12 || h < 12) return;
      const reduced = document.documentElement.dataset.reducedMotion === "true";
      const time = reduced ? 0 : performance.now() * 0.007;
      ctx.save();
      ctx.globalAlpha = Math.min(1, Math.max(0, strength));
      // Thin frost bands, with no full-screen gradient allocation each frame.
      ctx.strokeStyle = "rgba(248, 253, 255, 0.38)";
      ctx.lineWidth = 2;
      ctx.strokeRect(1, 1, w - 2, h - 2);
      ctx.strokeStyle = "rgba(79, 128, 160, 0.13)";
      ctx.lineWidth = 1;
      ctx.strokeRect(3.5, 3.5, w - 7, h - 7);
      // Sixteen faint snow points; reduced motion fixes their positions.
      ctx.fillStyle = "rgba(250, 253, 255, 0.40)";
      for (let i = 0; i < 16; i += 1) {
        const x = (i * 71 + 23 + time * 0.22) % w;
        const y = (i * 113 + 17 + time * (1 + i % 3 * 0.2)) % h;
        ctx.fillRect(x, y, i % 4 === 0 ? 2 : 1, 1);
      }
      ctx.restore();
    }
  }
});
